name: pyside2
version: 'latest'
version-script: wget -qO- https://pypi.python.org/pypi/pyside2/json | jq .info.version | sed -e 's/^"//' -e 's/"$//'
summary: Qt for Python (Technology Preview) - Unofficial
description: |
  The Qt for Python product enables the use of Qt5 APIs in Python applications.
  It lets Python developers utilize the full potential of Qt, using the PySide2 module.
  The PySide2 module provides access to the individual Qt modules such as QtCore, QtGui, and so on.

grade: devel
confinement: strict

architectures:
  - build-on: amd64

slots:
  pyside2:
    interface: content
    read:
      - $SNAP/pyside

parts:
  pyside2:
    plugin: nil
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/pyside
      echo "Get latest release..."
      pip3 install --no-cache-dir pyside2 -t ${SNAPCRAFT_PART_INSTALL}/pyside
      rm -r ${SNAPCRAFT_PART_INSTALL}/pyside/PySide2/examples
    build-packages:
      - python3-pip
      - wget
      - jq
    stage-packages:
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libxrandr2
      - libasound2
      - libglu1-mesa
      - libgles2-mesa
      - libxkbcommon0
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - libxslt1.1
